### ISSUE TITLE
[PBP] The Settings page of Chromium crashes

### ISSUE THREAD

**Issue by amharris** [mrfixit2001/debian_desktop#15]
With the out-of-the-box/bundled installation on my Pinebook Pro and all updates installed, moments after opening the 'Settings' page in Chromium—a split second after it finishes rendering—it crashes.

So far, I've carried out the usual basic troubleshooting steps, including reboots and checking for any package updates, to no avail.

**Comment by PrincessLuna2253** [comment]
Can confirm, I'm having the exact same issue.

**Comment by matthewadie** [comment]
I can confirm this as well.

**Comment by nebocamin** [comment]
hi @mrfixit2001 , can you provide how you built the chromium, which flags/patches, so maybe we can tinker until we will have a chromium-pbp.deb to update it on our machines?

**Comment by mrfixit2001** [comment]
All - this is caused from the parameters included in the shortcut for chromium. These parameters were added to support Netflix playback by default, but they anger the settings page. If you remove these parameters from the shortcut, or just run chromium-browser from the command line, you will have no issues accessing settings.

The chromium and firefox packages are borrowed from an ubuntu repo :) The debian desktop update that I released today will auto-install the new version. You can find it here:
https://launchpad.net/ubuntu/xenial/armhf/chromium-browser/78.0.3904.108-0ubuntu0.16.04.1

**Comment by louisabraham** [comment]
Hi, I have the same issue. Could you confirm that clicking on "Update Script" in the menu bar of the preinstalled Debian is supposed to install this fix?

**Comment by mrfixit2001** [comment]
Yes, there is an update for chromium and it’s settings that will be installed to address this when you click the update icon.

**Comment by louisabraham** [comment]
Thanks for your answer. Unfortunately I did the updates before and the problem still happened. Is there a way to check if the updates were applied?

**Comment by mrfixit2001** [comment]
There shouldn’t be an issue afterwards, but if it hasn’t resolved then you can access settings by running chromium-browser from the command line without any flags. The flags that are in the shortcut are the reason the settings page isn’t opening, but those flags enable the Netflix and prime video playback.

**Comment by louisabraham** [comment]
Thank you for your answer. Actually, I wanted a way to test if the updates were applied because I encounter several problems (not just this one) that are supposed to be solved.

The chromium shortcut calls `chromium-browser --disk-cache-size=2147483648 --user-agent="Mozilla/5.0 (X11; CrOS armv7l 6946.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"` is this can help.

I can confirm launching chromium from the command line works.
